### ISSUE TITLE
MP medical check

### ISSUE THREAD

**Issue by Varghjort** [ZioPao/The-Only-Cure#101]
When I played with my friends, one of them got bitten in the arm, so I took my saw and took his hand but the thing is, after taking his hand and making medical check again, it still showed that he had his hand in the medical menu, even tho he claimed in his medical menu the arm was indeed gone. I play a doctor so I take care of everyone when someone needs bandages etc cuz I take all the first aid with me always. Kinda lost the immersion there. Not sure if the mod conflicts with First Aid Overhaul.

**Comment by ZioPao** [comment]
Hi, sorry for the late response. Generally the mod should be resilient to this kind of things, but I need to know if at least it "fixed" itself after a while, especially if you logged out and logged back in.
Thanks

**Comment by ZioPao** [comment]
I'm closing this since I didn't get any response.
