### ISSUE TITLE
corrupt disk

### ISSUE THREAD

**Issue by Smoke407** [ZioPao/The-Only-Cure#104]
**Describe the bug**
when i install it it gives me corrupt disk and brakes all my mods, to fix it I uninstall all my mods I tried to install only The Only Cure and it still gave me corrupt disk it could be my issue I had problems like this before with Dayz after installing mods

**To Reproduce**
1. Go to The Only Cure
2. Click on Subscribe
3. Go to downloads
4. See Corrupt Disk Error

**Logs**
Please upload your game logs too. Server logs are useful too. 

**Additional context**
if you guys know any way of fixing this please tell me thank you.

**Comment by ZioPao** [comment]
I'm not sure what you're referring to. Can you add a screenshot?
