### ISSUE TITLE
mod not in mod list?

### ISSUE THREAD

**Issue by cyroliss** [ZioPao/The-Only-Cure#107]
the mod is not showing up on my mod list, i've already tried removing the old version and installing it by subscribing and by manually installing it into my files.

**Comment by marc-hg** [comment]
having the same issue

**Comment by ZioPao** [comment]
I might have broken something during the last update. I'll check it right now. Thank you for letting me know

**Comment by ZioPao** [comment]
@cyroliss @marc-hg Should be fixed. Let me know if everything is in order.

**Comment by cyroliss** [comment]
yupp all is good thanks man
