### ISSUE TITLE
Certain Timed Actions Do Not Work

### ISSUE THREAD

**Issue by ScherziSystemsMike** [ZioPao/The-Only-Cure#122]
**Describe the bug**
I restarted my Zomboid server at 9:15 after this mod updated, upon starting back up, players can no longer perform certain timed actions. Disassembling some furniture, and equipping items in your primary or secondary slot (except from your hotbar) result in an endlessly loading timed action. We have other mods on the server, but the update at 9:07 triggered whatever is happening.

**To Reproduce**
1. Attempt to equip and item using "Equip Primary" or "Equip Secondary"
2. You'll see a loading bar above your head as though you are about to perform a timed action, but cannot start it.
3. You'll have to hit `escape` to cancel the timed action.

**Logs**
No errors in the server logs.

**Comment by ZioPao** [comment]
Got a report already, I've reverted back to 2.1.2 for now.

**Comment by criticap** [comment]
> Got a report already, I've reverted back to 2.1.2 for now.

Still having same issue tho... The only things I can do is making Amputation+Prosthesis skill back to Lv9...

**Comment by ZioPao** [comment]
> > Got a report already, I've reverted back to 2.1.2 for now.
> 
> Still having same issue tho... The only things it can work is to make Formality skill back to Lv9 or below...

Unrelated bug, following in #129
