### ISSUE TITLE
Cannot use some animations after Left/Right reaches level 10/ familiarity reaches level 10,

### ISSUE THREAD

**Issue by ghost** [ZioPao/The-Only-Cure#127]
**Describe the bug**
Cannot use some animations after Left or Right reaches level 10 and/or familiarity reaches level 10 after amputation and prosthesis is equipped.  

**To Reproduce**
reach level 10 in the new skills with prosthesis equippted
**Logs**
none

**Additional context**
cannot consolidate all items and cannot refill tires with pump
once you remove the prosthesis, action can still be used as normal.

**Comment by GlarkGlark** [comment]
this is in single player

**Comment by GlarkGlark** [comment]
Just now i accidently selected amputate instead of bandage, and my right arm is now completely gone. as if it happened instantly. very disappointing. i know its my fault but IT IS an issue.

**Comment by GlarkGlark** [comment]
great. my 3 year old character is completely broken now due to a 3 cm. misclick, thanks author!

**Comment by ZioPao** [comment]
Reset your amputations in debug mode. 
I have no time for now to work on modding and nobody's paying me to do so, so chill the fuck out.

**Comment by GlarkGlark** [comment]
lol its funny you only respond when your ego is hurt. uninstalling the mod also works for anyone else who got screwed.

**Comment by ZioPao** [comment]
tracking the issue in #129
