### ISSUE TITLE
Timed actions cancelling before completion with high enough amputation/prosthesis skills

### ISSUE THREAD

**Issue by ScrooblesMcDoodle** [ZioPao/The-Only-Cure#129]
It seems that something about speeding up actions globally with prosthetics appears to be breaking things.

Playing instruments from Lifestyles, as well as attempting any form of timed action, speeds up the process immensely and cancels the action before it fully finishes.

It speeds up the process faster and faster until it cancels the action. So for instance something like consolidating thread, it speeds up super fast and then cancels once it reaches super-speed, meaning that you have to select consolidate again, and again, and again until the task is finally finished.

**Comment by ScrooblesMcDoodle** [comment]
Might be worth noting that this is a MP issue

**Comment by ScrooblesMcDoodle** [comment]
Hello??

**Comment by criticap** [comment]
Yeah, this happened to me too. Single player here.

**Comment by ScrooblesMcDoodle** [comment]
Dang, so it's not just a multiplayer thing. Seems like a core issue with the mod itself. I'm not exactly holding my breath waiting for a fix. From the looks of things the author doesn't have the time to work on this mod at the moment, which is disappointing but understandable. There are more important things in life, I get it. All that being said, this is big enough of an issue for me to not want to continue using this until it gets fixed.

**Comment by ZioPao** [comment]
Seems related to the skill level of the prosthetic, as said in #127 reported in #122

**Comment by ZioPao** [comment]
Should be fixed with #144
