### ISSUE TITLE
Modular Prosthetics

### ISSUE THREAD

**Issue by ZioPao** [ZioPao/The-Only-Cure#13]
- [x] Auto generation of XMLs, TXT, etc. via Python
- [ ] Implement correct values
- [ ] Find a decent way to manage the checks to get how much the prosthesis will affect speed
- [ ] Durability functionality for prosthesis

**Comment by persephonesPoms** [comment]
If I may, adding improvised prosþetics could be a good idea! Using tape or rags + a short blunt/long blunt (hand/forearm) weapon to use as an improvised second hand could be nice, as it's basically impossible to survive wiþout þe recipe.
(Plus, it would be metal AF to tape a crowbar to þe stump of your forearm.)

It probably shouldn't reduce þe speed penalty þat much, but it'd let you do two-handed tasks for a time wiþout having to search for þe recipe.
