### ISSUE TITLE
Can´t use pistols and revolvers with a amputated right hand.

### ISSUE THREAD

**Issue by IvanKMZ** [ZioPao/The-Only-Cure#134]
So, thats basically it.

I try removing the weapons mod I was using too, and the problem persists.

I can´t use pistols or revolvers without the right hand. Melee weapons are just fine.

What I noticed that may be related to the issue is that instead of my left hand leveling up, is my right hand that is doing so, but it is amputated.

Any possible fix to it?

**Comment by 4nalMac** [comment]
That's not an issue with this mod. Brutal handwork, the mod that allows you to fight with your left hand doesn't support using guns yet.
