### ISSUE TITLE
[Feature Request] - Makeshift Tourniquet

### ISSUE THREAD

**Issue by jeromethejust** [ZioPao/The-Only-Cure#135]
I think adding the ability to craft makeshift tourniquet's or use belts as a tourniquet would be an improvement. I know it might make things a little easier so for players that want the challenge could potentially disable the feature? Or make makeshift tourniquet's less effective than ones found in hospitals?

In terms of realism makeshift tourniquet's are a pretty common concept.

![image](https://github.com/user-attachments/assets/4f37195c-a908-40fe-a7ef-7ec2609ab55e)

**Comment by ZioPao** [comment]
Better to leave something like this in the discussions.
