### ISSUE TITLE
the TOC debug option doesnt appear in singleplayer

### ISSUE THREAD

**Issue by maxiharda4** [ZioPao/The-Only-Cure#137]
as i stated, i cant see the TOC debug option when right clicking on myself
it does not appear

**Comment by ZioPao** [comment]
Are you in debug mode?

**Comment by maxiharda4** [comment]
yeah

сб, 12 окт. 2024 г. в 20:41, Pao ***@***.***>:

**Comment by ZioPao** [comment]
Should be fixed with #144
