### ISSUE TITLE
Timed action slowness

### ISSUE THREAD

**Issue by ogwarf** [ZioPao/The-Only-Cure#146]
**Describe the bug**

Please be patient, this is my first bug report!
Context: I play on a server with several other amputees. 
We're at high amputee related skill levels. 
With the new update today, we have noticed a drastic reduction in the speed that timed actions take place. 

**To Reproduce**
1. Left side & right side level 7
2. Familiarity level 8
3. Both forearms amputated, cicatrized & cauterized
4. Two prosthetic arms equipped.

**Logs**
I'm not sure how to upload logs, and I do not have access to server logs. Sorry!

**Additional context**
I assume this is a bug (looking at the change notes)? 
I'm guessing it's related to '- Fixed perks (Prosthetics and Amputations) that, at some level, would make various timed actions impossible'
Please forgive me if this is an intended feature.

**Comment by ZioPao** [comment]
Hi, yeah there was a bug that would completely break actions at a certain point related to the high level of the modded perks.

Now the cap is set back to the original time needed to perform the action, you can't get faster than that. Before there was no actual cap, breaking things.

I hope this explains things
