### ISSUE TITLE
Losing Limb Slows down Reading

### ISSUE THREAD

**Issue by DaveyJey** [ZioPao/The-Only-Cure#18]
Losing a limb slows down timed actions, this totally makes sense; however, it seems that reading is considered a timed action and is thus also slowed down pretty significantly. I understand that there could be an argument that it takes longer to turn a page with just one hand, but turning pages only realistically accounts for like 5% of reading. Most time reading is spent *reading* which is not hindered by losing a hand or arm.

Additionally, two out of the three prosthetic books you can find in the world require you to have 4-8 levels of metalworking to create- which would require a good amount of reading to achieve.

If there is some way to make reading exempt from the timed action debuff, I think it would make this mod much much better.

**Comment by ZioPao** [comment]
Hey, in the current version this is taken care of, some actions won't be slowed down by losing a limb (like reading).
By current, I mean the one I'm still working on and that's not released on the workshop (files are already here on GitHub though).

**Comment by DaveyJey** [comment]
That's great to hear! I'm looking through the master branch now, super happy with all changes I've noticed so far. Looking forward to when the new release goes live!
