### ISSUE TITLE
Mod strings not working on linux

### ISSUE THREAD

**Issue by cheloide** [ZioPao/The-Only-Cure#19]
The current workshop mod has the `Translate` folder named with lowercase and linux paths are case sensitive preventing the path from being read and causing string variable names being shown instead of the right text.

![image](https://github.com/ZioPao/The-Only-Cure/assets/11063780/dcfafe45-78b6-4514-be08-bdd6e070ab61)

How it looks with the current workshop mod under linux:
![image](https://github.com/ZioPao/The-Only-Cure/assets/11063780/964fc700-a7ff-4646-8027-06404a680011)

How it looks with the folder name fixed:
![image](https://github.com/ZioPao/The-Only-Cure/assets/11063780/054c70fc-053c-4351-bfd9-bc35e4bb0ba9)

**Comment by ZioPao** [comment]
Sorry, I know about this. It's already fixed in the current version. It will be fixed when I release the current version on the Workshop.
