### ISSUE TITLE
Hook item stuck in inventory

### ISSUE THREAD

**Issue by 13acts** [ZioPao/The-Only-Cure#20]
I found an annoying bug that broke the game. Here are the steps to recreate, applies for multiplayer.
1. Have another player wear a prosthetic hook
2. The other player die
3. Go to their body and see an item called Left Hand - Wooden Hook in their inventory
4. Grab the item

The item will be transferred to your inventory, and then you won't be able to interact with it anymore, ie. when right click on the item, all the prompts including Unpack, Favorite, Inspect, Equip, Place item, are clickable but won't have any effect.
Upon restarting the server, I noticed that the hook is now equipped to my character, and the model of the hook render overlapping with the model of the vanilla hand. I also cannot interact with the item. Upon examining The Only Cure menu (one with figures of 2 arms), both arms appear to be normal.

**Comment by ZioPao** [comment]
Hi, this is with the current version on the workshop?

**Comment by 13acts** [comment]
> Hi, this is with the current version on the workshop?

Considering the mod was updated on 11th, and my bug occurred on 8th, I assume it's of a previous version.
I haven't attempted to recreate the bug in the latest version.

**Comment by ZioPao** [comment]
> > Hi, this is with the current version on the workshop?
> 
> Considering the mod was updated on 11th, and my bug occurred on 8th, I assume it's of a previous version. I haven't attempted to recreate the bug in the latest version.

The current version on GitHub is a lot different than the one on the workshop. I'm finalizing some stuff before I can push on it on the workshop, those kind of issues shouldn't happen anymore.
