### ISSUE TITLE
Stuttering on right click

### ISSUE THREAD

**Issue by zeroryuk** [ZioPao/The-Only-Cure#22]
Hi, I'm having issues with treating wounds and stuff. I got it after cutting an arm of one of my friend and I got to lvl 10 first aid. Everytime I right click now when trying to remove bandages or pick what treatment I want to do the game freezes a little. this can get people killed specially on the neck. This is my only mod related to medicines so please check what is causing this. I don't get any error also.

**Comment by ZioPao** [comment]
Shouldn't happen anymore with the next version since it's a total rewrite.
