### ISSUE TITLE
Mod compatibility issue "Inventory Tetris": Cut arm can be removed from its utility slot

### ISSUE THREAD

**Issue by Sheffie7** [ZioPao/The-Only-Cure#26]
Inventory Tetris mod shows the slot that cut arm is using, and so player can just remove it from there and get his hand back, atleast outwardly.

Steps to reproduce:
1. Start with a cut arm trait.
2. It is not showed for a first few minutes after spawn, but later, probably when arm gets dirty/bloody, it appears in equipment slots.

Just guessing, maybe you could know how to fix that.

Screenshot:
![theonlycuremod](https://github.com/ZioPao/The-Only-Cure/assets/44413884/7fa7a220-f159-4045-8ccd-174c09b21b2f)

Mod link: https://steamcommunity.com/sharedfiles/filedetails/?id=2982070344

**Comment by RosinRush** [comment]
When combined with rain wash it can be dropped from the inventory entirely (learned this accidentally, was very confused)

**Comment by RosinRush** [comment]
^ fixed upon restarting.
