### ISSUE TITLE
Cannot equip backpacks or put on clotches

### ISSUE THREAD

**Issue by Bartusso** [ZioPao/The-Only-Cure#27]
When the mod is installed, you are unable to put on clothing (pretty sure its all clothing haven`t tested all tho) like shirts, socks, shoes and other. You are also unable to equip backpacks but only on your back. The fannypacks still work tho. 
This is consistent both on hosted server and on single player.
In both instances the mod was added before the world was first opened (generated).

**Comment by ZioPao** [comment]
Hi, thank you for reporting it. Sorry for the issue, it should be fixed now. I pushed an update on the workshop, let me know if it works now. 1bef713de554ab272e625f5d70596ffd2cc877ec

**Comment by Bartusso** [comment]
The update fixed the issue.
Also damn you were so fast with the fix.

**Comment by ZioPao** [comment]
> The update fixed the issue. Also damn you were so fast with the fix.

Just a fairly stupid issue that I should have seen coming. Happy to hear that it's all good now :)
