### ISSUE TITLE
Backpacks

### ISSUE THREAD

**Issue by Clone4082** [ZioPao/The-Only-Cure#30]
I am unable to equip backpacks, vanilla or otherwise, while this mod is installed. I am given the option to put one on, but my character does not initiate the action, and it will stay in their inventory

**Comment by ZioPao** [comment]
> I am unable to equip backpacks, vanilla or otherwise, while this mod is installed. I am given the option to put one on, but my character does not initiate the action, and it will stay in their inventory

Hi, I'm unable to reproduce this as of now. There was a bug before that would cause this issue but it has been patched. Are you sure you're running the updated mod? Try to unsubscribe and resubscribe, let me know if it works after that.

**Comment by Clone4082** [comment]
Huh...I tried that earlier before posting this, but that seems to have done the trick. Thanks for the assist
