### ISSUE TITLE
bug reports are increasing forever + if you start with amputated trait amputated hand model not showing

### ISSUE THREAD

**Issue by ExileWind** [ZioPao/The-Only-Cure#32]
first error: bottom right corner the error messages increasing during entire gameplay it reaches around 4k

[coop-console.txt](https://github.com/ZioPao/The-Only-Cure/files/15208107/coop-console.txt)
[console.txt](https://github.com/ZioPao/The-Only-Cure/files/15208108/console.txt)

second error: if you start with amputated trait your left hand is still there not cutted off

**Comment by ExileWind** [comment]
Additional note: the first error only happens when I host a coop server

**Comment by ZioPao** [comment]
> Additional note: the first error only happens when I host a coop server

Hi, thank you for adding this note. The mod has been developed with SP and MP with dedicated servers, but not the host option. I'll see if it can be fixed, but as of now the Hosting a server from within the game isn't really supported.

**Comment by ZioPao** [comment]
Traits were broken as of 2.0.1. They should be fixed now with 2.0.2
If you can, provide me with some logs for the first errors related to the co-op issues

**Comment by JagersDiabetes** [comment]
This issue has also been happening on my Dedicated server. Co-admin removed the mod so we dont have logs.

**Comment by ZioPao** [comment]
> This issue has also been happening on my Dedicated server. Co-admin removed the mod so we dont have logs.

If you can, test again with the current version. The error spam shouldn't happen anymore

**Comment by ExileWind** [comment]
thanks mate thoose 2 bugs are fixed :)

**Comment by hmitch22** [comment]
Getting the same logged error message in a dedicated server - has anything changed since 2.0.2 that might affected this?

**Comment by ZioPao** [comment]
Without logs I can't help. Please post them

**Comment by hmitch22** [comment]
> Without logs I can't help. Please post them

Apologies! I have attached them
[server-console.txt](https://github.com/ZioPao/The-Only-Cure/files/15422890/server-console.txt)
[console.txt](https://github.com/ZioPao/The-Only-Cure/files/15422891/console.txt)

**Comment by NemoSomnium** [comment]
Hello, I'm experiencing the same problem.
Running dedicated server with the mod and whenever starting with any of the 3 amputated traits the error counter starts climbing to the thousands.
Eventually kicked me and my friend from my server.
