### ISSUE TITLE
medical check doesnt work in mp / health menu breaks after death

### ISSUE THREAD

**Issue by urristec** [ZioPao/The-Only-Cure#34]
Trying to perform medical check on others causes a bunch of error messages to appear, making a new character after having your amputee character die causes the break of health menu. Sadly don't have any screenshots of error messages as i didn't think of actually reporting this yesterday 
P.S: the server didn't have any mods that could potentially intervene with health system

**Comment by ZioPao** [comment]
Hi, without logs it's a bit difficult to pinpoint the problem.
Did errors start appearing right after you did a medical check on other players or after you did something in particular?
By "break of health menu", what do you mean? What happens?

**Comment by ZioPao** [comment]
Also, this is with the Host option from the game, not a real dedicated server, correct? If so, that mode is currently unsupported.

**Comment by ZioPao** [comment]
Found a problem that would prevent users from opening the Medical Check on other players when no amputation were present. Now it should be fixed. I'll wait for some confirmation on your end before closing the issue.

**Comment by urristec** [comment]
```
-----------------------------------------
function: getIsCut -- file: DataController.lua line # 232 | MOD: The Only Cure
function: getDamagedParts -- file: HealthPanel.lua line # 272 | MOD: The Only Cure
function: updateBodyPartList -- file: ISHealthPanel.lua line # 526 | Vanilla
function: update -- file: ISHealthPanel.lua line # 396 | Vanilla
function: update -- file: HealthPanel.lua line # 133 | MOD: The Only Cure

LOG  : General     , 1714921882902> 211 201 847> -------------------------------------------------------------
attempted index: Hand_L of non-table: null

LOG  : General     , 1714921882903> 211 201 848> -----------------------------------------
STACK TRACE
-----------------------------------------
function: getIsCut -- file: DataController.lua line # 232 | MOD: The Only Cure
function: getDamagedParts -- file: HealthPanel.lua line # 272 | MOD: The Only Cure
function: updateBodyPartList -- file: ISHealthPanel.lua line # 526 | Vanilla
function: update -- file: ISHealthPanel.lua line # 396 | Vanilla
function: update -- file: HealthPanel.lua line # 133 | MOD: The Only Cure

ERROR: General     , 1714921882904> 211 201 849> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: Hand_L of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1714921882904> 211 201 850> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: Hand_L of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1827)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:38)
	at zombie.ui.UIElement.update(UIElement.java:1589)
	at zombie.ui.UIElement.update(UIElement.java:1606)
	at zombie.ui.UIElement.update(UIElement.java:1606)
	at zombie.ui.UIManager.update(UIManager.java:1042)
	at zombie.GameWindow.logic(GameWindow.java:262)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:765)
	at zombie.GameWindow.run_ez(GameWindow.java:681)
	at zombie.GameWindow.mainThread(GameWindow.java:495)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1714921882907> 211 201 852> -----------------------------------------
STACK TRACE
-----------------------------------------
function: getIsCut -- file: DataController.lua line # 232 | MOD: The Only Cure
function: getDamagedParts -- file: HealthPanel.lua line # 272 | MOD: The Only Cure
function: updateBodyPartList -- file: ISHealthPanel.lua line # 526 | Vanilla
function: update -- file: ISHealthPanel.lua line # 396 | Vanilla
function: update -- file: HealthPanel.lua line # 133 | MOD: The Only Cure
```
That's the error log appearing after dying as amputee character
Also, it seems that i'm now unable to perform any actions; equipping clothes, weapons or anything doesn't work and creates an error i inserted above.
It should be also mentioned that i don't get any wounds on me either, like i'm losing health but i don't get any injuries on me
![20240505181811_1](https://github.com/ZioPao/The-Only-Cure/assets/104390612/9cc62889-348a-4812-b00b-fe434e2fa37b)
![20240505180357_1](https://github.com/ZioPao/The-Only-Cure/assets/104390612/392b9355-ef88-4ee2-9f0e-25db800590bd)

the only mods we had were TOC:R, Shark and Cytt's Kentucky Car Overhaul, both fancy and brutal handwork

**Comment by ZioPao** [comment]
> ```
> -----------------------------------------
> function: getIsCut -- file: DataController.lua line # 232 | MOD: The Only Cure
> function: getDamagedParts -- file: HealthPanel.lua line # 272 | MOD: The Only Cure
> function: updateBodyPartList -- file: ISHealthPanel.lua line # 526 | Vanilla
> function: update -- file: ISHealthPanel.lua line # 396 | Vanilla
> function: update -- file: HealthPanel.lua line # 133 | MOD: The Only Cure
> 
> LOG  : General     , 1714921882902> 211 201 847> -------------------------------------------------------------
> attempted index: Hand_L of non-table: null
> 
> LOG  : General     , 1714921882903> 211 201 848> -----------------------------------------
> STACK TRACE
> -----------------------------------------
> function: getIsCut -- file: DataController.lua line # 232 | MOD: The Only Cure
> function: getDamagedParts -- file: HealthPanel.lua line # 272 | MOD: The Only Cure
> function: updateBodyPartList -- file: ISHealthPanel.lua line # 526 | Vanilla
> function: update -- file: ISHealthPanel.lua line # 396 | Vanilla
> function: update -- file: HealthPanel.lua line # 133 | MOD: The Only Cure
> 
> ERROR: General     , 1714921882904> 211 201 849> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: Hand_L of non-table: null at KahluaThread.tableget line:1689.
> ERROR: General     , 1714921882904> 211 201 850> DebugLogStream.printException> Stack trace:
> java.lang.RuntimeException: attempted index: Hand_L of non-table: null
> 	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
> 	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
> 	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
> 	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
> 	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1827)
> 	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:38)
> 	at zombie.ui.UIElement.update(UIElement.java:1589)
> 	at zombie.ui.UIElement.update(UIElement.java:1606)
> 	at zombie.ui.UIElement.update(UIElement.java:1606)
> 	at zombie.ui.UIManager.update(UIManager.java:1042)
> 	at zombie.GameWindow.logic(GameWindow.java:262)
> 	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
> 	at zombie.GameWindow.frameStep(GameWindow.java:765)
> 	at zombie.GameWindow.run_ez(GameWindow.java:681)
> 	at zombie.GameWindow.mainThread(GameWindow.java:495)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> LOG  : General     , 1714921882907> 211 201 852> -----------------------------------------
> STACK TRACE
> -----------------------------------------
> function: getIsCut -- file: DataController.lua line # 232 | MOD: The Only Cure
> function: getDamagedParts -- file: HealthPanel.lua line # 272 | MOD: The Only Cure
> function: updateBodyPartList -- file: ISHealthPanel.lua line # 526 | Vanilla
> function: update -- file: ISHealthPanel.lua line # 396 | Vanilla
> function: update -- file: HealthPanel.lua line # 133 | MOD: The Only Cure
> ```
> 
> That's the error log appearing after dying as amputee character Also, it seems that i'm now unable to perform any actions; equipping clothes, weapons or anything doesn't work and creates an error i inserted above. It should be also mentioned that i don't get any wounds on me either, like i'm losing health but i don't get any injuries on me ![20240505181811_1](https://private-user-images.githubusercontent.com/104390612/328028523-9cc62889-348a-4812-b00b-fe434e2fa37b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MjMwMDgsIm5iZiI6MTcxNDkyMjcwOCwicGF0aCI6Ii8xMDQzOTA2MTIvMzI4MDI4NTIzLTljYzYyODg5LTM0OGEtNDgxMi1iMDBiLWZlNDM0ZTJmYTM3Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQxNTI1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWE5ZjU2NDc4YWU4NWU3MWM2MjVmZGZiOTY4ZjBjMjE0ODM2Yjk5MGI0ODhhZTQ3ODI5ZGNjMjcxYTg1MGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YFcxh2rBEIoKCMxSLL8d-xMuR7TFl6pQAQ4x7bQPkys) ![20240505180357_1](https://private-user-images.githubusercontent.com/104390612/328028528-392b9355-ef88-4ee2-9f0e-25db800590bd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MjMwMDgsIm5iZiI6MTcxNDkyMjcwOCwicGF0aCI6Ii8xMDQzOTA2MTIvMzI4MDI4NTI4LTM5MmI5MzU1LWVmODgtNGVlMi05ZjBlLTI1ZGI4MDA1OTBiZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQxNTI1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZThmM2ZmNTU3ODg2MWIxNmZiOGNhMjkxZjMxZGYxOGYyYzA3ZjFiNjkxNDQwNWViMGUzNWJhMjFmYmRmMTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G462zQDuyj7tmtp0h3MTBAc3TOq2QspxMjY1RYTY3Ig)
> 
> the only mods we had were TOC:R, Shark and Cytt's Kentucky Car Overhaul, both fancy and brutal handwork this issue appears both as host and client.

I'd need the full logs if that's possible

**Comment by urristec** [comment]
I'll just attach my entire console.txt file
[console.txt](https://github.com/ZioPao/The-Only-Cure/files/15213510/console.txt)

**Comment by ZioPao** [comment]
Thank you. Seems like TOC failed to initialize. From what I'm seeing, this is a co-op game, which is "supported" but not tested on. What happens if you start with a new character? Does it still break?

**Comment by urristec** [comment]
Bug still remains even after creating a new character, the only solution to that being creation of an entirely new world

**Comment by ZioPao** [comment]
Sorry, I should have specified. I meant a new character with a new name.

**Comment by urristec** [comment]
Named my character a completely different name, still doesn't work
Can't find the reset button for some reason, it's simply not there.
![2024-05-05_19-07-35](https://github.com/ZioPao/The-Only-Cure/assets/104390612/98432c01-f302-4cdf-aa70-248257ca0439)

**Comment by urristec** [comment]
Resetting amputations worked, although it made my character unable to open doors via E key for some reason??? (clicking on them worked, error did not appear)
Changing my name also worked, fixing broken character entirely.
