### ISSUE TITLE
I cant carry 1 handed weapons with my prothestic hand

### ISSUE THREAD

**Issue by SebbyLikesCats** [ZioPao/The-Only-Cure#35]
Title

**Comment by ZioPao** [comment]
Hey, I really need more info. Which limb did you cut? Did any errors appear?

**Comment by SebbyLikesCats** [comment]
My Right hand
No Errors

**Comment by ZioPao** [comment]
Found a problem, I'm pushing an update now. Let me know if it's fixed.

**Comment by Edelrauschen** [comment]
seems to work now

**Comment by ZioPao** [comment]
Thank you for letting me know! I'll close this issue
