### ISSUE TITLE
familiarity skill does not go up

### ISSUE THREAD

**Issue by Edelrauschen** [ZioPao/The-Only-Cure#40]
hey mate, great work - i love that mod. first time i cut of my hand, the sound gave me shivers! 🗡️ 

as the titel states, the familiarity trait seems not to level up.

**Comment by ZioPao** [comment]
Hi! By "familiarity", are you referring to the Prosthesis familiarity trait, correct? If so, I think I may have forgot about enabling the level up 😅 . A fix will come out shortly, thank you for letting me notice

**Comment by Edelrauschen** [comment]
yes exactly, the prosthesis familiarity trait. appreciation for your work! 👍

**Comment by ZioPao** [comment]
I've pushed an update on the Workshop
3199596
9478e0f

**Comment by Edelrauschen** [comment]
yep, bar started to fill up. nice work! Also two questions from me: 1) could you add in the description the possibility of kauterization of the stump? that`s a pretty essential info, discovered only by accident. 2) any plans to include prosthetics for legs in the future?

**Comment by ZioPao** [comment]
> yep, bar started to fill up. nice work! Also two questions from me: 1) could you add in the description the possibility of kauterization of the stump? that`s a pretty essential info, discovered only by accident. 2) any plans to include prosthetics for legs in the future?

1) Good call, I forgot about that. I'll add it in a bit
2) Yeah, but I wanted to push out this "rebuilt" version before going all-in on that
