### ISSUE TITLE
Arm stays dirty after cleaning character

### ISSUE THREAD

**Issue by lucasbmichels** [ZioPao/The-Only-Cure#43]
Hello developers! 

I'm having an issue regarding the cleaning of the character where the amputated arm stays dirty.

I don't know if it is a mod conflict or your mod only.

Thank you in advance!

![dirty arm](https://github.com/ZioPao/The-Only-Cure/assets/168977632/f73ba145-8b49-4519-a701-e46d5da747fe)

**Comment by ZioPao** [comment]
Hey, yeah it's a bug on my end. I should be able to fix this fairly easily.
Keep in mind that the wound dirtyness related to the amputation is still gonna be separate from the washing process, just so you know.

**Comment by ZioPao** [comment]
#44 
Pushed it on the workshop, let me know if everything seems ok now

**Comment by lucasbmichels** [comment]
Hey Pao, it didn't work, unfortunately.

**Comment by ZioPao** [comment]
Just to be sure, you tried washing your character again, right?

**Comment by lucasbmichels** [comment]
Yep

**Comment by lucasbmichels** [comment]
I even tried using debug mode to remove dirt and blood

**Comment by ZioPao** [comment]
I think I found the problem. I'm gonna make some adjustments and then let you know when it's actually fixed. Sorry for the bug.

**Comment by ZioPao** [comment]
Pushed it, let me know if it works now.

**Comment by lucasbmichels** [comment]
Hey there, well, i tried in my current save and it didn't work, but in a new save it worked.

And thanks for the fix, no need to apologize.

Your mod is awesome!

**Comment by lucasbmichels** [comment]
Update, i don't know how i did it but it worked on my current save, hahaha, thanks again!
