### ISSUE TITLE
Incompatibilities with previous TOC 1.0

### ISSUE THREAD

**Issue by Nerdgamerdave** [ZioPao/The-Only-Cure#48]
**Describe the bug**
Solo Play appears to have zero issues.  Successfully severed arms, healed and used as expected.  

No errors in -debug mode.

Character 1: "Abby" Amputated arm via old mod.  Killed off character.  Installed new TOC mod.  Created new character.

Upon Loading into MP server (Dedicated Server hosted on Indifferent broccoli), Infinite errors.

logging in using -Debug mode, server breaks and lists the following stacktrace:

Function: getIsCut--DataController.lua line #232 | MOD: The Only Cure
Function: getDamagedParts--file: HealthPanel.lua line #272 | MOD: The Only Cure
Function: updateBodyPartList --file:ISHealthPenel.lua line #526 | Vanilla
Function: update -- file: ISHealthPanel.lua line # 396 | Vanilla
Function: update -- file: HealthPanel.lua line # 133 | MOD The Only Cure

Character 2, 3 and Admin account:

No issues or errors.

**To Reproduce**

Killed off character 1 "Abby" again.   Exit to desktop.  Reload game and created new character.

Loaded into game.  Infinite Errors.

Loaded in as other characters and admin account.  Zero errors.

**Screenshots**
N/A

**Additional context**

Data from the old TOC mod appears to be "stuck" to character accounts that had any amputations prior.  When loading in as any such character, infinite errors occur as if the old data is still present in the character profile/login.

The old mod data may be "baked" into those characters, unable to remove without a server wipe, unless there is a way to fully purge a character/account from a server.

**Comment by ZioPao** [comment]
Hi, would you be able to provide me with the full logs?
