### ISSUE TITLE
Can`t equip items in hands in MP

### ISSUE THREAD

**Issue by Bartusso** [ZioPao/The-Only-Cure#50]
The bug prevents players from equiping weapons in primary, secondary or in both hands in MP.
Seems like it stanrted to occur after  v2.0.7 (after on 6 May 5:17 pm)
Weapons can still be add to hotkeys (1-3) but when pressed they do nothing.
Both host and clients are affected by this. With a exception that a host of the server who had his arm amputated (wearing prosthesis) was able to do everything normally.
This bug doesn`t seem to affect singleplayer.

To Reproduce
1. Boot up a multiplayer session
2. Attempt to equip weapons in primary, secondary or in both hands or by using hotkeys (1-3)
3. Weapons are unable to be equipped

[06-05-24_21-49-05_DebugLog.txt](https://github.com/ZioPao/The-Only-Cure/files/15225788/06-05-24_21-49-05_DebugLog.txt)

**Comment by ZioPao** [comment]
I think I missed something when I pushed 2.0.7, sorry for that. 
#51 should fix it

**Comment by Bartusso** [comment]
#51 fixed the bug
