### ISSUE TITLE
Can't bandage bleeding caused by amputations

### ISSUE THREAD

**Issue by RubyRedsword** [ZioPao/The-Only-Cure#53]
**Describe the bug**
anytime you saw off you left or right arm you will be forever bleeding even after its cauterized and the stitching is removed, eve possible for it to have the bleeding debuff while it is bandage

**To Reproduce**
1. Go to limb wanted to
2. Click on amputate limb and do the care for it
3. and typically just wait

**Logs**
i cant seem to find the logs other wise i would even though it does show up as an error hopefully the images help

![20240507013940_1](https://github.com/ZioPao/The-Only-Cure/assets/168946486/46d807fb-b009-44ea-990c-893aba41f991)

![20240507013914_1](https://github.com/ZioPao/The-Only-Cure/assets/168946486/26b59381-62fc-4283-b041-6986355554bb)

**Comment by RubyRedsword** [comment]
i have them equipped but as you can see in the seoncd image the left arm is still bleedin even when it is fully cicatrized, from what i seen it tends to not go away, but it also seems to have issues equipping two prosthesis as well. as i tried wearing it but it wouldn't get equipped.

**Comment by ZioPao** [comment]
Found the issue. Bleeding was set incorrectly and could get "over" bandages. In theory, if you've got a bandage, the bleeding should still be there and you'll have to keep your bandages clean and that should be it.

For that character, you will have to wait until the bleeding stops I'm afraid. You could toggle it from debug mode and fix it that way.

I'll push an update shortly with the fix included (c1faeea)

**Comment by ZioPao** [comment]
I'll assume this is fixed. If you need more help about this issue, feel free to re-open the issue.
