### ISSUE TITLE
scratched on prosthetic 

### ISSUE THREAD

**Issue by RubyRedsword** [ZioPao/The-Only-Cure#57]
**Describe the bug**
while wearing a prosthetic for a missing limb you can get scratched and bleed

**To Reproduce**
1. wear prosthetic on missing limb
2. get injured
3. See error
4. not sure if it applies if you aren't wearing it just came across it while wearing one
image of it
![20240509043227_1](https://github.com/ZioPao/The-Only-Cure/assets/168946486/45cb6f52-06de-4f2c-b730-240afeb89d91)

**Comment by ZioPao** [comment]
Hi, some logs would be extremely helpful.

**Comment by RubyRedsword** [comment]
oh! it was bleeding, just had to be in a safe spot before pressing f12! and im not sure how to grab those logs even after the time frame it has been, sorry

**Comment by ZioPao** [comment]
I really need logs, I can't help without those. I can't reproduce the issue.

**Comment by RubyRedsword** [comment]
also it seems you are missing both hands at least you aren't able to open doors, wondering if that intended

**Comment by ZioPao** [comment]
> also it seems you are missing both hands at least you aren't able to open doors, wondering if that intended

That's intended

**Comment by ZioPao** [comment]
> thank you! that's all I've for now. only other thing I've been wonder is if legs prothesis would be available in the future, probably should of started a new post ofr that question

Yeah, they're in the works, no ETA though.
