### ISSUE TITLE
Mod Incompatibilities with Immersive Medicine

### ISSUE THREAD

**Issue by Leonisiord** [ZioPao/The-Only-Cure#61]
Hey, im in a server where we are trying to introduce Immersive Medicine and The Only Cure at the same time. We have the issue that The Only Cure disables the Immersive Medicine health menu, hiding the bodyparts when they are not injured, and then we can't use the medicines like Alkagin which are supuse to be used in the head in the health menu even if you are not injured in the head. 

Im not sure if you are understanding me, im not very good at English. If you can find a solution. Im not an admin of that server, but I really want to make both mods work.

**Comment by Ilya0Walker** [comment]
bump

**Comment by Br3nnabee** [comment]
Same here :/

**Comment by MRFELIXSENIOR** [comment]
same here 2 months later

**Comment by m-hynek** [comment]
try this meanwhile https://steamcommunity.com/sharedfiles/filedetails/?id=3290132940
its TOC + IM + braven antizin fix patch (not including the mods, original mods needed)

im using it on my server

**Comment by ZioPao** [comment]
Hi, I've added a compat check for immersive medicine in the current dev version, I just forgot to push it out on the main branch and publish it on the Workshop 😅 
@m-hynek what was wrong with Braven Antizin? I could add that fix directly into the mod.

**Comment by m-hynek** [comment]
correct

**Comment by ZioPao** [comment]
#105 is pushed on the Workshop, it adds Immersive Medicine support. External patches shouldn't be necessary anymore
