### ISSUE TITLE
Bitten on my hand after Hand After Amputated

### ISSUE THREAD

**Issue by SebbyLikesCats** [ZioPao/The-Only-Cure#62]
Title
![Screenshot 2024-05-10 161617](https://github.com/ZioPao/The-Only-Cure/assets/168876558/7fe10019-d8a2-4b96-a51b-bf2e40ce6b6a)

**Comment by ZioPao** [comment]
Logs please

**Comment by SebbyLikesCats** [comment]
> Logs please

how?

**Comment by SebbyLikesCats** [comment]
> Logs please

btw no errors shown

**Comment by ZioPao** [comment]
They're located in C:/Users/YOUR_NAME/Zomboid/console.log.

Even if it didn't throw out errors, they're ALWAYS helpful, so please post them.

**Comment by SebbyLikesCats** [comment]
> They're located in C:/Users/YOUR_NAME/Zomboid/console.log.
> 
> Even if it didn't throw out errors, they're ALWAYS helpful, so please post them.

nothing just start up stuff lemme look deeper

**Comment by ZioPao** [comment]
> > They're located in C:/Users/YOUR_NAME/Zomboid/console.log.
> > Even if it didn't throw out errors, they're ALWAYS helpful, so please post them.
> 
> nothing just start up stuff lemme look deeper

Just upload the file. You don't need to look into it, but I do

**Comment by SebbyLikesCats** [comment]
![Screenshot 2024-05-10 164752](https://github.com/ZioPao/The-Only-Cure/assets/168876558/c09870d8-a8d5-4be9-98b3-a5bdad04fdb2)
which one

**Comment by ZioPao** [comment]
console

**Comment by SebbyLikesCats** [comment]
[console.txt](https://github.com/ZioPao/The-Only-Cure/files/15280894/console.txt)

**Comment by SebbyLikesCats** [comment]
> console

this what you need?

**Comment by SebbyLikesCats** [comment]
You Find Anything?

**Comment by ZioPao** [comment]
Yes, you're running an older version for some reason. Try to unsub and re-sub and it should fix itself.
