### ISSUE TITLE
Amputation trait seems to give random skin colored arm.

### ISSUE THREAD

**Issue by 4nalMac** [ZioPao/The-Only-Cure#63]
after a few runs with the mod I noticed that when I would use the amputated trait (specifically the forearm one) My character would occasionally end up with a different skin tone for my arm than on the rest of my character.

**Comment by ZioPao** [comment]
Hey, can you give me a screenshot? It may be helpful to pinpoint what's happening. Thank you

**Comment by 4nalMac** [comment]
[console.txt](https://github.com/ZioPao/The-Only-Cure/files/15284245/console.txt)

**Comment by ZioPao** [comment]
Can you give me a screenshot of the "error" too?

**Comment by 4nalMac** [comment]
![20240512140240_1](https://github.com/ZioPao/The-Only-Cure/assets/48250280/1e02e71e-efd8-4f07-8078-4e7a185cbd79)
So I tried a few times with randomly generated characters and couldn't get it to happen but on my last attempt I decided to give it a try with a survivor that had body hair enabled. This seemed to do it. I also think the trait itself has nothing to do with it and it is in fact just survivors that have chest hair.

**Comment by ZioPao** [comment]
> ![20240512140240_1](https://private-user-images.githubusercontent.com/48250280/329870882-1e02e71e-efd8-4f07-8078-4e7a185cbd79.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NTA2MTgsIm5iZiI6MTcxNTU1MDMxOCwicGF0aCI6Ii80ODI1MDI4MC8zMjk4NzA4ODItMWUwMmU3MWUtZWZkOC00ZjA3LTgwNzgtNGU3YTE4NWNiZDc5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDIxNDUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MTE4NThhY2ZmNGQ0ODAzNzdkMDRjNjU3NjI2Y2QxZDM0MWVmYzliNDFmYWM0MWRkYWNjMjMzZjA5OGFiZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.57XuaZeGDqj9H9U97mYld1Gn60AQ_jjaaU3uMu1lj4s) So I tried a few times with randomly generated characters and couldn't get it to happen but on my last attempt I decided to give it a try with a survivor that had body hair enabled. This seemed to do it. I also think the trait itself has nothing to do with it and it is in fact just survivors that have chest hair.

This was an old issue that I was almost sure I fixed. I'll check it out again, thank you!

**Comment by ZioPao** [comment]
Found the issue, I must have re-added in the recent times.
Your current character will have the wrong skin color though until you get a new one I'm afraid.

I'll close the issue when I'm ready to push the update on the workshop
696edc1f1dac56fd92e24664ee05b064d61df602
