### ISSUE TITLE
Cauterize issue

### ISSUE THREAD

**Issue by sn4k334t3r** [ZioPao/The-Only-Cure#64]
Hello!

This may be the wrong place but I currently have an issue when trying to cauterize my arm, I get a prompt telling me that I don't "have the guts to do it."

Any idea what this means? Ive tried to take pills and drink in game to no avail.

Also am having an issue with the top half of my arm being the incorrect skin color and am not able to clean the nub, its at 100% dirt but it wont allow me to disinfect. It seems to have no consequence however and my character will be fine once I cauterize the arm.

Let me know if you have the solution.

Thanks!!

**Comment by ZioPao** [comment]
Hey, you need to have strength at level 5 or more or have the Brave trait to cauterize your wounds.

**Comment by sn4k334t3r** [comment]
Thanks so much! I couldn't find info on it anywhere online and I spent a couple hours.

I'm enjoying the mod a ton and the challenge of it.

Thanks for fixing and reuploading it! :-)
