### ISSUE TITLE
Double Amputee Can't Enter Vehicles

### ISSUE THREAD

**Issue by Lieutenant-Wub** [ZioPao/The-Only-Cure#65]
One of the friends I play with has had a tough time, requiring both of her bands to be cut off. After some time, the wounds have healed over, and two prosthetic arms have been crafted, which she is getting familiar with. 

However, ever since she lost her second hand, she has not been able to enter vehicles at all, even with both prosthetics equipped.

Is this an issue with familiarity, which will improve when her skill gets better? Is she just banned from ever using cars, even as a passenger? Is it an issue with some of the car mods we have?

Happy to provide more information as required.

**Comment by Lieutenant-Wub** [comment]
Alright, it seems to have been a familiarity issue - she's level 4 now and can now enter vehicles.

Apologies for the inconvenience.

**Comment by ZioPao** [comment]
Hey, nope it's not intended, this is actually a bug. Thank you for reporting it. I'll look into it

**Comment by Lieutenant-Wub** [comment]
We're having issues with it again. here's what's happening so far:

We started the session with both arms on, she was able to use vehicles.
She went to sleep with both arms off, and can no longer use vehicles.
She went back to sleep with both arms **on**, but still can't use vehicles.
She left the session, and her game froze. She needed to alt+f4.
She relaunched the game, joined the session, and can use vehicles. 

[console.txt](https://github.com/ZioPao/The-Only-Cure/files/15286150/console.txt)

**Comment by ZioPao** [comment]
Found the issue, I will push an update with a fix shortly

**Comment by ZioPao** [comment]
Fixed with 5f64ead3547692f0b4f576f43ef75c7c7e87bd03
I will close the issue once I get a confirmation that everything is ok

**Comment by Lieutenant-Wub** [comment]
Character has died, so we can't test the double amputee issues anymore. Will report when the circumstances are met again.

**Comment by Lieutenant-Wub** [comment]
No problem, I'll let you know!
