### ISSUE TITLE
question/potential bug

### ISSUE THREAD

**Issue by Julianjj1** [ZioPao/The-Only-Cure#69]
When a doctor cuts off a patient's hand, he doesn't get experience. it was there in the old version, is it intentional or a bug?

**Comment by ZioPao** [comment]
It's a missing feature. Thank you for letting me notice.

**Comment by Julianjj1** [comment]
no problem If I may ask, when do you plan to add it back?

**Comment by Julianjj1** [comment]
2 question Will you make another version of this mod, only with legs, or will you add the option to cut off the legs to this mod?

**Comment by ZioPao** [comment]
> no problem If I may ask, when do you plan to add it back?

No ETA, sorry.

> 2 question Will you make another version of this mod, only with legs, or will you add the option to cut off the legs to this mod?

It will be an addition, not another separated mod
