### ISSUE TITLE
Question about future plans

### ISSUE THREAD

**Issue by LIBERTY-PC** [ZioPao/The-Only-Cure#70]
**Amputations for the legs**
will there be a feature where you can also amputate the characters legs? so when you get surprised by the crawler your char will have a chance when he/she is bitten in the legs?

**More/Different types of prosthetics**
will there be other types/models of prosthetics in the future? like full limb or just the hand?

i also want to say that this is a really cool mod and you have made a really good job making it. its defiantly gonna be in all my playthroughs

**Comment by ZioPao** [comment]
hi!
1) Yes, I still plan to add it. No ETAs though. No specifics about the functionality for now since most of the work was done in a previous version of The Only Cure and it's no longer applicable to the current one
2) Planned, but for now it has low priority compared to legs.
