### ISSUE TITLE
Missing hand? (the wrong one)

### ISSUE THREAD

**Issue by Minkyyyyyyy** [ZioPao/The-Only-Cure#73]
Amputated my character's left forearm, but my right hand is now missing as well.

**Comment by ZioPao** [comment]
Hi.
Please, add logs when you post an issue and maybe some screenshots to show the issue.

**Comment by invisiblesic** [comment]
hey there,

I am having the same issue in multiplayer. However, while I can not see my unamputated hand, my friend can.
![Screenshot 2024-06-29 152123](https://github.com/ZioPao/The-Only-Cure/assets/174210915/5409548d-fb01-4bf1-adcd-7569d46cda24)
