### ISSUE TITLE
Clothing Clipping/Amputate using Shotgun

### ISSUE THREAD

**Issue by K4zs** [ZioPao/The-Only-Cure#76]
**Describe the bug**
You can amputate your arm using a sawed off shotgun, literally cut your arm with the barrel.
Another issue is some clothes, especially clothes from spongies clothing, clip in between the prosthetic, the prosthetic goes through the sleeve, maybe make the prosthetic not so bulky?

**To Reproduce**
1. Go to 'game'
2. Click on 'sawed off shotgun'
3. Scroll down to 'amputate'

**Additional context**
none

**Comment by ZioPao** [comment]
Fixed the shotgun thing, thank you for letting me know
