### ISSUE TITLE
I can't play with him

### ISSUE THREAD

**Issue by CocoNegrinho8** [ZioPao/The-Only-Cure#77]
I have a question, the mod when I play it in single player or mp appears in red in the list of mods and I try to install it again, it doesn't change. Could you help me or explain?
 

![Captura de pantalla 2024-06-01 012917](https://github.com/ZioPao/The-Only-Cure/assets/171300878/58d9073b-4651-470f-a5ee-11d27932a965)

**Comment by ZioPao** [comment]
It's related to how I handle logging, it doesn't impact the mod from working. I will try to fix it at a later time, but for normal users as of now it's a non-issue.
