### ISSUE TITLE
How do I activate the mods?

### ISSUE THREAD

**Issue by sebatunyu** [ZioPao/The-Only-Cure#81]
I have done it according to the order of the mods but there is always an error notification, I have created a new saveslot several times but the results are still the same, I have also re-downloaded it on Steam Workshop and the result is always an error.

![messageImage_1717574254991](https://github.com/ZioPao/The-Only-Cure/assets/171784073/e6a75bb8-8c75-424a-8e2f-68d8c255e08a)

**Comment by ZioPao** [comment]
The error is related to how I handle the logging. That doesn't mean that the mod isn't working. You can safely ignore that.
