### ISSUE TITLE
Amputation traits do not grant cicatrization

### ISSUE THREAD

**Issue by Flat-Cap** [ZioPao/The-Only-Cure#86]
**Describe the bug**
When spawning in with a new character using the left hand amputated trait the wound isn't cicatrized from the beginning. I'm not sure if this was intended but the older versions didn't have this problem.

**To Reproduce**
1. Go to 'Character Creation'
2. Click on 'Left Hand Amputated trait'
3. Then spawn the character into the new world and open the health tab

**Comment by ZioPao** [comment]
Not intended, will fix in the next version

**Comment by gordingus** [comment]
Is this why I gradually gain sickness over time when I start with it?

**Comment by ZioPao** [comment]
> Is this why I gradually gain sickness over time when I start with it?

Depending on your mod list, if you have some mod that make you sick when you have wounds, then yes.
Anyway, resolved in v2.0.15.
